AMQP_URI: 'pyamqp://guest:guest@rabbitmq'
WEB_SERVER_ADDRESS: '0.0.0.0:8999'
rpc_exchange: 'nameko-rpc'

CLOUDINARY:
  cloud_name: 'dd3xkz9pg'
  api_key: 759897756355147
  api_secret: KI51PQlCAl19j0uEVUYaw9Bp8II
